stages:
  - package
  - deploy

package:
  image: docker:latest
  stage: package
  variables:
    IMAGE_NAME: emmerce-api
  before_script:
    - echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_ID --password-stdin
  script:
    # Docker 이미지 빌드
    - docker build -t $DOCKER_HUB_USER/$IMAGE_NAME .
    - docker push $DOCKER_HUB_USER/$IMAGE_NAME
  after_script:
    - docker logout
  only:
    - master
  tags:
    - dev

deploy:
  image: docker:latest
  stage: deploy
  variables:
    IMAGE_NAME: emmerce-api
    CONTAINER_NAME: emmerce-api-container
  before_script:
    - echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_ID --password-stdin
  script:
    - docker stop $CONTAINER_NAME || true
    - docker rm $CONTAINER_NAME || true
    - docker rmi -f $DOCKER_HUB_USER/$IMAGE_NAME || true
    - docker image prune -f
    - docker pull $DOCKER_HUB_USER/$IMAGE_NAME
    - docker run -d --restart always -p 8088:8088 --name $CONTAINER_NAME $DOCKER_HUB_USER/$IMAGE_NAME
  after_script:
    - docker logout
  only:
    - master
  tags:
    - dev
