spring:
  # 콘솔 텍스트 색깔 설정
  output:
    ansi:
      enabled: always
  profiles:
    active: local

# R2DBC에서 Database로 나가는 쿼리를 보고 싶을 때
logging:
  level:
    org.springframework.r2dbc.core: debug

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
  live:
    # 7일
    rtk: 604800000

spring-doc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter : method
    doc-expansion : none

# AWS S3
cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION_STATIC}
      auto: false
    stack:
      auto: false

# 카카오페이 admin key
kakao:
  admin-key: ${KAKAO_ADMIN_KEY}
